#!/usr/bin/env bash
set -eu
export LC_ALL=C

cat <<EOF
#cloud-config
# Before commit any change please validate this file @ https://coreos.com/validate/

# Set hostname
hostname: ${_NODE_HOSTNAME}

# Set SSH Key
ssh_authorized_keys:
- ${NODE_PUBLIC_KEY}

coreos:
  update:
    reboot-strategy: ${COREOS_REBOOT_STRATEGY:-"etcd-lock"}
  units:
    - name: docker.service
      drop-ins:
      - name: 20-docker-opts.conf
        content: |
          [Service]
          Environment="DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=5"
    - name: systemd-networkd.service
      command: stop
    - name: 00-${NODE_NET_DEVICE}.network
      runtime: true
      content: |
        [Match]
        Name=${NODE_NET_DEVICE}

        [Network]
        DNS=${NODE_DNS}
        Address=${_NODE_ADDRESS}/${NODE_NETWORK_RANGE}
        Gateway=${NODE_GATEWAY}
    - name: down-interfaces.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set ${NODE_NET_DEVICE} down
        ExecStart=/usr/bin/ip addr flush dev ${NODE_NET_DEVICE}
    - name: systemd-networkd.service
      command: restart
    - name: swap.service
      enable: true
      contents: |
        [Unit]
        Description=Turn on swap

        [Service]
        Type=oneshot
        Environment="SWAP_PATH=/var/vm"
        Environment="SWAP_FILE=swapfile1"
        ExecStartPre=-/usr/bin/rm -rf ${SWAP_PATH}
        ExecStartPre=/usr/bin/mkdir -p ${SWAP_PATH}
        ExecStartPre=/usr/bin/touch ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/bin/bash -c "fallocate -l 2048m ${SWAP_PATH}/${SWAP_FILE}"
        ExecStartPre=/usr/bin/chmod 600 ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/usr/sbin/mkswap ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/usr/sbin/sysctl vm.swappiness=10
        ExecStart=/sbin/swapon ${SWAP_PATH}/${SWAP_FILE}
        ExecStop=/sbin/swapoff ${SWAP_PATH}/${SWAP_FILE}
        ExecStopPost=-/usr/bin/rm -rf ${SWAP_PATH}
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target
EOF
